import Head from 'next/head'
import styles from '../styles/Home.module.css'
import { useDispatch, useSelector } from 'react-redux'
import { updateName } from '../features/randomName/randomNameSlice'

export default function Home() {

  const state = useSelector((state) => state)
  const dispatch = useDispatch()

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
        <h1> NextJS Shopping Cart </h1>
        <h2> {state.name} </h2>
    <button 
      onClick={() => dispatch(updateName())}>
        Change Name
    </button>
    </div>
  )
}
